---
- name: Ensure that Thunderbird is present
  become: true
  ansible.builtin.dnf:
    name:
      - thunderbird
      - thunderbird-wayland
    state: present

- name: Ensure that Tangram is present
  community.general.flatpak:
    name: re.sonny.Tangram
    state: present
