---
- name: Set up apps for communication
  ansible.builtin.import_tasks: communication.yaml

- name: Set up apps for writing prose
  ansible.builtin.import_tasks: prose.yaml

- name: Set up password manager
  ansible.builtin.include_tasks: password_manager.yaml

- name: Ensure that Errands to-do application is present
  community.general.flatpak:
    name: io.github.mrvladus.List
    state: present
