---
- name: Set up apps for communication
  ansible.builtin.import_tasks: communication.yaml

- name: Set up apps for writing prose
  ansible.builtin.import_tasks: prose.yaml

- name: Ensure that Errands to-do application is present
  community.general.flatpak:
    name: io.github.mrvladus.List
    state: present

- name: Ensure that Anki is present
  community.general.flatpak:
    name: net.ankiweb.Anki
    state: present
