---
# https://docs.fedoraproject.org/en-US/quick-docs/installing-plugins-for-playing-movies-and-music/
- name: Ensure multimedia libraries from default repositories are present
  become: true
  ansible.builtin.dnf:
    name:
      - gstreamer1-plugins-bad-*
      - gstreamer1-plugins-good-*
      - gstreamer1-plugins-base
      - gstreamer1-plugin-openh264
      - gstreamer1-plugin-libav
      - lame*
    exclude:
      - gstreamer1-plugins-bad-free-devel
      - lame-devel
    state: present

# TODO: Add 'intel-media-driver' task? VAAPI support?
# See https://rpmfusion.org/Howto/Multimedia for details.
