#!/usr/bin/env bash
# HLWM CONFIG
# ---------------------------

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# FUNCTION
# ---------------------------

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

# hlwm kill
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

# execute
hc keybind $Mod-Return spawn kitty
# hc keybind $Mod-Shift-Return spawn kitty tmux attach
hc keybind $Mod-e spawn thunar 
# hc keybind $Mod-Shift-e spawn kitty ranger
hc keybind $Mod-Shift-space spawn ~/.config/herbstluftwm/status.sh
hc keybind $Mod-space spawn rofi -m -2 -show run -disable-history -font "IBM Plex Mono 14"
hc keybind $Mod-m spawn ~/.config/herbstluftwm/bat_stat.sh
hc keybind $Mod-v spawn ~/.config/herbstluftwm/clip-mpv.sh

# multimedia
hc keybind XF86AudioMute chain , spawn amixer -q -D pulse set Master toggle , emit_hook sound
hc keybind XF86AudioRaiseVolume chain , spawn amixer -q -D pulse set Master 5%+ , emit_hook sound
hc keybind XF86AudioLowerVolume chain , spawn amixer -q -D pulse set Master 5%- , emit_hook sound
hc keybind XF86AudioMicMute chain , spawn amixer -q -D pulse set Capture toggle , emit_hook mic_sound
hc keybind XF86MonBrightnessUp chain , spawn xbacklight -inc 5 , emit_hook backlight
hc keybind XF86MonBrightnessDown chain , spawn xbacklight -dec 5 , emit_hook backlight

# close windows
hc keybind $Mod-w close_or_remove

# focusing clients
hc keybind $Mod-h     focus left 
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right 

# moving clients (multimonitor support)
hc keybind $Mod-Shift-h or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-j or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-k or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-l or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# rotating clients
# hc keybind $Mod-comma chain , lock , rotate , rotate , rotate , unlock
# hc keybind $Mod-period rotate
hc keybind $Mod-period chain , lock , rotate , rotate , unlock

# splitting frames
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-i       split explode
hc keybind $Mod-y       remove

# resizing frames
resizestep=0.05
hc keybind $Mod-Alt-h       resize left +$resizestep
hc keybind $Mod-Alt-j       resize down +$resizestep
hc keybind $Mod-Alt-k       resize up +$resizestep
hc keybind $Mod-Alt-l       resize right +$resizestep

# tags
tag_names=( {1..4} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
done

hc floating 4 on

hc keybind $Mod-n	use_index -1 #--skip-visible
hc keybind $Mod-m	use_index +1 #--skip-visible
hc keybind $Mod-Shift-n	move_index -1 #--skip-visible
hc keybind $Mod-Shift-m	move_index +1 #--skip-visible
hc keybind Alt-Tab cycle

# layout
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
#hc keybind $Mod-m emit_hook minimal_layout
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Tab                                                           \
            chain ,, or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid   \
               , cycle_layout +1 ,, emit_hook layout_changed

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 resize

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule title='Steam Keyboard' manage=off
hc rule title='Steam' tag=4

# FORM
# ---------------------------
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# frames
hc set frame_gap 0
hc set frame_padding 0
hc set frame_border_width 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 1
hc set always_show_frame 0
hc set smart_frame_surroundings 0
hc set frame_active_opacity 80
hc set frame_normal_opacity 0

# windows
hc set window_border_width 4
hc set window_border_inner_width 0
hc set window_border_active_color '#C29C51'
hc set window_border_normal_color '#222222'
hc set window_border_inner_color '#222222'
hc set window_gap 0
hc set smart_window_surroundings 0

# floating
hc set snap_distance 30
hc set snap_gap 0
hc set mouse_recenter_gap 0
hc set raise_on_focus 1
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color '#222222'

# colors
# focused
hc attr theme.active.color '#C29C51'
hc set frame_border_active_color '#222222'
hc set frame_bg_active_color '#C29C51'
hc attr theme.urgent.color orange

# unfocused
hc attr theme.normal.color '#454545'
hc set frame_border_normal_color '#222222'
hc set frame_bg_normal_color '#222222'
#hc attr theme.inner_width 1
#hc attr theme.outer_width 1
#hc attr theme.outer_color '#222222'
#hc attr theme.inner_color '#222222'
#hc attr theme.border_width 3
#hc attr theme.background_color '#222222'

hc set default_frame_layout 0

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# hc set_monitors 1920x1080+0+0 1920x1080+0+0
# or simply:
hc detect_monitors
hc set auto_detect_monitors 1
#if [[ $(xrandr | grep "^DP-.* connected") ]]; then
hc pad 0 0 0 0 0
# hc pad 1 0 0 40 0
#else
# hc pad 0 0 0 40 0
#fi

# START ON LAUNCH
# ---------------------------
feh --bg-fill ~/.config/herbstluftwm/wall.jpg &
if hc silent new_attr bool my_not_first_autostart ; then
  #picom &
  unclutter -idle 3 &
  redshift -l '34.683437:-82.837364' -b 1.0:0.75 &
  #~/.config/herbstluftwm/bar.sh &
else
  notify-send -t 2000 'hlwm reloaded'
fi
