---
- name: Ensure that KeePassXC is present
  become: true
  ansible.builtin.dnf:
    name: keepassxc
    state: present

- name: Ensure that tray icon is enabled
  community.general.ini_file:
    path: "{{ keepassxc_config_file_location }}"
    section: GUI
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: "644"
    state: present
  loop: "{{ kp_config_data | dict2items }}"
  vars:
    kp_config_data:
      MinimizeOnClose: "true"
      MinimizeToTray: "true"
      ShowTrayIcon: "true"
      TrayIconAppearance: monochrome-light

- name: Ensure that extension support is enabled
  community.general.ini_file:
    path: "{{ keepassxc_config_file_location }}"
    section: Browser
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: "644"
    state: present
  loop: "{{ kp_config_data | dict2items }}"
  vars:
    kp_config_data:
      CustomProxyLocation: ""
      Enabled: "true"

- name: Ensure SSH agent is enabled
  community.general.ini_file:
    path: "{{ keepassxc_config_file_location }}"
    section: SSHAgent
    option: Enabled
    value: "true"
    no_extra_spaces: true
    mode: "644"
    state: present
