---
- name: Ensure that desktop autostart folder exists
  ansible.builtin.file:
    path: "{{ local_autostart_location }}"
    state: directory
    mode: "755"

- name: Prevent keyring daemon from starting on login
  ansible.builtin.copy:
    src: hidden.desktop
    dest: "{{ local_autostart_location }}/{{ item }}"
    mode: "644"
  loop:
    - gnome-keyring-pkcs11.desktop
    - gnome-keyring-secrets.desktop
    - gnome-keyring-ssh.desktop

- name: Enable KeePassXC Secret Service integration
  community.general.ini_file:
    path: "{{ keepassxc_config_file_location }}"
    section: FdoSecrets
    option: Enabled
    value: "true"
    no_extra_spaces: true
    mode: "644"
    state: present

- name: Ensure that local DBus service folder exists
  ansible.builtin.file:
    path: "{{ local_user_dbus_location }}"
    state: directory
    mode: "755"

- name: Override DBus secrets service file with KeePassXC
  ansible.builtin.copy:
    src: org.freedesktop.secrets.service
    dest: "{{ local_user_dbus_location }}/org.freedesktop.secrets.service"
    mode: "644"

- name: Ensure that local user systemd units folder exists
  ansible.builtin.file:
    path: "{{ local_user_systemd_location }}"
    state: directory
    mode: "755"

- name: Ensure SSH agent service file is present
  ansible.builtin.copy:
    src: ssh-agent.service
    dest: "{{ local_user_systemd_location }}/ssh-agent.service"
    mode: "644"

- name: Start SSH agent service on boot
  ansible.builtin.systemd_service:
    name: ssh-agent
    scope: user
    state: started
    enabled: true

- name: Check if SSH_AUTH_SOCK environment variable is present
  ansible.builtin.lineinfile:
    path: "{{ local_bash_profile_location }}"
    line: export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
    state: present
  check_mode: true
  register: ssh_auth_sock_status

- name: Remove previous SSH_AUTH_SOCK reference
  ansible.builtin.lineinfile:
    path: "{{ local_bash_profile_location }}"
    regexp: ^(export )?SSH_AUTH_SOCK=
    state: absent
  when: ssh_auth_sock_status is changed # noqa: no-handler

- name: Export SSH_AUTH_SOCK environment variable
  ansible.builtin.lineinfile:
    path: "{{ local_bash_profile_location }}"
    line: export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
    state: present

# DBus initiates secrets service on login, would rather not suddenly see a window then.
- name: Do not show KeePassXC window on startup
  community.general.ini_file:
    path: "{{ keepassxc_config_file_location }}"
    section: GUI
    option: MinimizeOnStartup
    value: "true"
    no_extra_spaces: true
    mode: "644"
    state: present
