---
- name: Assert that currently running operating system is Fedora
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Fedora"
    quiet: true
    fail_msg: Role cannot be executed on non-Fedora operating system

# https://rpmfusion.org/Configuration
# https://rpmfusion.org/keys
- name: Import RPM Fusion GPG free key
  ansible.builtin.rpm_key:
    key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}
    state: present

- name: Enable the RPM Fusion free repository
  ansible.builtin.dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Import RPM Fusion GPG non-free key
  ansible.builtin.rpm_key:
    key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}
    state: present
  when: rpm_fusion_non_free_is_enabled

- name: Enable the RPM Fusion non-free repository
  ansible.builtin.dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: rpm_fusion_non_free_is_enabled
