---
- name: Ensure that tray icon extension is present
  become: true
  ansible.builtin.dnf:
    name: gnome-shell-extension-appindicator
    state: present

- name: Enable extensions
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['appindicatorsupport@rgcjonas.gmail.com']"
    state: present
