---
- name: Set up Git
  ansible.builtin.include_tasks: git.yaml

- name: Set up Ansible tooling
  ansible.builtin.import_tasks: ansible.yaml

- name: Set up Builder IDE
  ansible.builtin.import_tasks: builder.yaml
