---
- name: Ensure Builder IDE is present
  become: true
  ansible.builtin.dnf:
    name: gnome-builder

- name: Set Builder editor font
  community.general.dconf:
    key: /org/gnome/builder/editor/font-name
    value: "'{{ font_monospace }}'"
    state: present
