---
- name: Ensure Builder IDE is present
  become: true
  ansible.builtin.dnf:
    name: gnome-builder

- name: Set Builder editor font
  community.general.dconf:
    key: /org/gnome/builder/editor/font-name
    value: "'{{ font_monospace }}'"
    state: present

- name: Set Builder terminal font
  community.general.dconf:
    key: /org/gnome/builder/terminal/font-name
    value: "'{{ font_monospace }}'"
    state: present

- name: Set Builder color scheme
  community.general.dconf:
    key: /org/gnome/builder/editor/style-scheme-name
    value: "'solarized-light'"
    state: present

- name: Set Builder interface style
  community.general.dconf:
    key: /org/gnome/builder/style-variant
    value: "'light'"
    state: present

- name: Show grid lines in Builder
  community.general.dconf:
    key: /org/gnome/builder/editor/show-grid-lines
    value: true
    state: present
