---
- name: Ensure Git is present
  become: true
  ansible.builtin.dnf:
    name: git
    state: present

- name: Ensure credentials are present in Git configuration
  community.general.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
    state: present
  loop: "{{ git_config_data | dict2items }}"
  vars:
    git_config_data:
      user.name: "{{ full_name }}"
      user.email: "{{ email }}"

- name: Ensure that Commit message editor is present
  community.general.flatpak:
    name: re.sonny.Commit
    state: present

- name: Use Commit as editor by default when committing
  community.general.git_config:
    name: core.editor
    value: flatpak run re.sonny.Commit
    scope: global
    state: present

- name: Ensure that Gittyup Git client is installed
  community.general.flatpak:
    name: com.github.Murmele.Gittyup
    state: present
