---
- name: Ensure Git is present
  become: true
  ansible.builtin.dnf:
    name: git
    state: present

- name: Ensure credentials are present in Git configuration
  community.general.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
    state: present
  loop: "{{ git_config_data | dict2items }}"
  vars:
    git_config_data:
      user.name: "{{ full_name }}"
      user.email: "{{ email }}"
