profile=gpu-hq

# GUI
osd-font='Fira Code'
osd-font-size=12

# youtube-dl
ytdl-format=bestvideo[height<=?2160]+bestaudio/best
# ytdl-format=bestvideo[height<=?480]+bestaudio/best
ytdl-raw-options=sub-lang=en,write-sub=,write-auto-sub=

#force-window=immediate
#vo=gpu
#gpu-api=vulkan
#video-sync=display-resample
hwdec=vdpau

ao=pulse,alsa
