num_context_lines 7
pygments_style monokai

foreground       #d0d0d0
background       #0a0b09

# File headers
title_fg       #d0d0d0
title_bg       #0a0b09

# Columns
margin_fg       #d0d0d0
margin_bg       #0a0b09

# Hunk headers
hunk_margin_bg       #5d6b5b
hunk_bg              #5d6b5b

# Added
added_bg             #2c6024
added_margin_bg      #2c6024
highlight_added_bg   #2c6024

# Removed
removed_bg           #60242c
highlight_removed_bg #60242c
removed_margin_bg    #60242c
