# Fonts
font_family IBM Plex Mono
bold_font IBM Plex Mono Bold
italic_font IBM Plex Mono Italic
bold_italic_font auto

font_size 14
disable_ligatures cursor

# Markers
map f1 create_marker
map f2 remove_marker

# Tabs/window management
map ctrl+shift+t launch --cwd=current --type=tab
map ctrl+shift+p previous_tab
map ctrl+shift+n next_tab
map shift+super+enter launch --cwd=current --type=os-window
tab_fade 1

remember_window_size  no
initial_window_width  640
initial_window_height 400

# Misc
enable_audio_bell no
window_padding_width 10 
update_check_interval 0

# Colors
foreground       #d0d0d0
background       #0a0b09
color0   #2c4001
color0   #2c4001
color1   #5e7b24
color9   #5e7b24
color2   #89a64b
color10  #89a64b
color3   #728c3b
color11  #728c3b
color4   #8bb530
color12  #8bb530
color5   #728c3b
color13  #728c3b
color6   #b6b450
color14  #b6b450
color7   #d0d0d0
color15  #c5c8c6
